// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD8rOmuuz3ZLBpQmyx9seitVC1HaDBsqs',
    appId: '1:384412785920:web:7c33bb80be58c9c5d1e7e5',
    messagingSenderId: '384412785920',
    projectId: 'flutter-catalog-18829',
    authDomain: 'flutter-catalog-18829.firebaseapp.com',
    storageBucket: 'flutter-catalog-18829.appspot.com',
    measurementId: 'G-MJMPJRG8S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBMi-e1LP1KxGskJ_Sy_LB0TCTK9en2ek',
    appId: '1:384412785920:android:2dfd117047708257d1e7e5',
    messagingSenderId: '384412785920',
    projectId: 'flutter-catalog-18829',
    storageBucket: 'flutter-catalog-18829.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOYGLr-6OUUmqeUG3Kkv-ir9roj2OeMwE',
    appId: '1:384412785920:ios:61608585051d95c5d1e7e5',
    messagingSenderId: '384412785920',
    projectId: 'flutter-catalog-18829',
    storageBucket: 'flutter-catalog-18829.appspot.com',
    iosClientId: '384412785920-qgkr110s4uu9d444ah358ldmvvtgkp3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOYGLr-6OUUmqeUG3Kkv-ir9roj2OeMwE',
    appId: '1:384412785920:ios:61608585051d95c5d1e7e5',
    messagingSenderId: '384412785920',
    projectId: 'flutter-catalog-18829',
    storageBucket: 'flutter-catalog-18829.appspot.com',
    iosClientId: '384412785920-qgkr110s4uu9d444ah358ldmvvtgkp3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGui',
  );
}
